#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1558633367                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
webstore_link                             : './webapp/index.html'
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : # https://play.google.com/store/apps/details?id=com.thinkinhd.randomchess                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Random Chess - Fun Learning                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Generate fully randomized Chess board and play with friends anytime, anywhere.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Think in HD                               
your_link                                 : https://thinkinhd.com                     
your_city                                 : Hanoi                                
email_address                             : contact@thinkinhd.com
facebook_username                         : huydung1406                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : huydung
youtube_username                          : UC4-2wFF3rIe3nmbNViJqCyw



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fully Randomized Board
    description                           : <strong>Maximum fun and slightly "unfair" - The mode that small kids LOVE!</strong> <br/><br/>All the pieces are randomized and pawns can be placed on either the first or second rows! The only two rules are (1) King must not be exposed on the front-line and (2) Bishops must be in squares of opposite colors. Black and White starts with totally different different positions most of the time. 
    fontawesome_icon_name                 : random
    
  - title                                 : Chess960 board
    description                           : <strong>Recognized by FIDE, the fun cnad challenging mode for serious players!</strong><br/><br/> In this mode, all the pawns are in standard positions, the other pieces are randomized on the usual row with respect to three rules (1) King must be in between the two rooks, (2) Bishops must be in squares of opposite colors, and (3) Black pieces are mirrored from White pieces. 
    fontawesome_icon_name                 : sort

  - title                                 : 2-players play on device
    description                           : <strong>Specifically optimized game play for two players directly on the device</strong>.<br/><br/>There are unlimited Undo, you can either Drag-and-Drop or Click-and-Click to make a move, there are extremely clear indicator and animations of whose turn is this and which piece is chosen for a move, plus hidden surprises. Play a game to see it for yourself.
    fontawesome_icon_name                 : user-friends  



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#0b0b0b"
cover_overlay_transparency                : 0.6

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#53000b"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#be012a"
feature_text_color                        : "#333333"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#53000b"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#53000b"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown